"""empty message

Revision ID: 14f4965331e8
Revises: 4487cfe71200
Create Date: 2024-10-09 00:30:37.994773

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14f4965331e8'
down_revision = '4487cfe71200'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('planetas',
    sa.Column('ID_Planeta', sa.Integer(), nullable=False),
    sa.Column('Rotation_Period', sa.Integer(), nullable=False),
    sa.Column('Orbital_Period', sa.Integer(), nullable=False),
    sa.Column('Gravity', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('ID_Planeta')
    )
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.drop_column('Name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Name', sa.VARCHAR(length=250), autoincrement=False, nullable=False))

    op.drop_table('planetas')
    # ### end Alembic commands ###
