"""empty message

Revision ID: 4487cfe71200
Revises: 5c748846dfee
Create Date: 2024-10-07 23:48:03.697704

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4487cfe71200'
down_revision = '5c748846dfee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Name', sa.String(length=250), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.drop_column('Name')

    # ### end Alembic commands ###
