"""empty message

Revision ID: 46a294384f83
Revises: 14f4965331e8
Create Date: 2024-10-09 01:01:19.895859

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46a294384f83'
down_revision = '14f4965331e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuario',
    sa.Column('ID_Usuario', sa.Integer(), nullable=False),
    sa.Column('Nombre', sa.String(length=250), nullable=False),
    sa.Column('Apellido', sa.String(length=250), nullable=False),
    sa.Column('Correo', sa.String(length=250), nullable=False),
    sa.Column('Password', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('ID_Usuario')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usuario')
    # ### end Alembic commands ###
