"""empty message

Revision ID: 5c748846dfee
Revises: a5cffa318ac2
Create Date: 2024-10-07 23:44:15.869553

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c748846dfee'
down_revision = 'a5cffa318ac2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('people',
    sa.Column('Id_Personajes', sa.Integer(), nullable=False),
    sa.Column('Birthline', sa.Integer(), nullable=False),
    sa.Column('Gender', sa.String(length=250), nullable=False),
    sa.Column('Height', sa.Integer(), nullable=False),
    sa.Column('Skin_color', sa.String(length=250), nullable=False),
    sa.Column('Eye_color', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('Id_Personajes')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('people')
    # ### end Alembic commands ###
