"""empty message

Revision ID: 5e554c0156e8
Revises: 
Create Date: 2024-10-11 01:17:42.012496

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e554c0156e8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('personajes',
    sa.Column('Id_Personajes', sa.Integer(), nullable=False),
    sa.Column('Birthline', sa.Integer(), nullable=False),
    sa.Column('Gender', sa.String(length=250), nullable=False),
    sa.Column('Height', sa.Integer(), nullable=False),
    sa.Column('Skin_color', sa.String(length=250), nullable=False),
    sa.Column('Eye_color', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('Id_Personajes')
    )
    op.create_table('planetas',
    sa.Column('ID_Planeta', sa.Integer(), nullable=False),
    sa.Column('Rotation_Period', sa.Integer(), nullable=False),
    sa.Column('Orbital_Period', sa.Integer(), nullable=False),
    sa.Column('Gravity', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('ID_Planeta')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('usuario',
    sa.Column('ID_Usuario', sa.Integer(), nullable=False),
    sa.Column('Nombre', sa.String(length=250), nullable=False),
    sa.Column('Apellido', sa.String(length=250), nullable=False),
    sa.Column('Correo', sa.String(length=250), nullable=False),
    sa.Column('Password', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('ID_Usuario')
    )
    op.create_table('datos__favoritos',
    sa.Column('id_Favoritos', sa.Integer(), nullable=False),
    sa.Column('user_Id', sa.Integer(), nullable=True),
    sa.Column('Planeta_ID', sa.Integer(), nullable=True),
    sa.Column('Personajes_Id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['Personajes_Id'], ['personajes.Id_Personajes'], ),
    sa.ForeignKeyConstraint(['Planeta_ID'], ['planetas.ID_Planeta'], ),
    sa.ForeignKeyConstraint(['user_Id'], ['usuario.ID_Usuario'], ),
    sa.PrimaryKeyConstraint('id_Favoritos')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('datos__favoritos')
    op.drop_table('usuario')
    op.drop_table('user')
    op.drop_table('planetas')
    op.drop_table('personajes')
    # ### end Alembic commands ###
