"""empty message

Revision ID: 90942878daf8
Revises: f3af458c6a2d
Create Date: 2024-10-09 05:16:44.319906

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90942878daf8'
down_revision = 'f3af458c6a2d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('personajes',
    sa.Column('Id_Personajes', sa.Integer(), nullable=False),
    sa.Column('Birthline', sa.Integer(), nullable=False),
    sa.Column('Gender', sa.String(length=250), nullable=False),
    sa.Column('Height', sa.Integer(), nullable=False),
    sa.Column('Skin_color', sa.String(length=250), nullable=False),
    sa.Column('Eye_color', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('Id_Personajes')
    )
    op.drop_table('people')
    with op.batch_alter_table('datos__favoritos', schema=None) as batch_op:
        batch_op.drop_constraint('datos__favoritos_Personajes_Id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'personajes', ['Personajes_Id'], ['Id_Personajes'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('datos__favoritos', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('datos__favoritos_Personajes_Id_fkey', 'people', ['Personajes_Id'], ['Id_Personajes'])

    op.create_table('people',
    sa.Column('Id_Personajes', sa.INTEGER(), server_default=sa.text('nextval(\'"people_Id_Personajes_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('Birthline', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('Gender', sa.VARCHAR(length=250), autoincrement=False, nullable=False),
    sa.Column('Height', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('Skin_color', sa.VARCHAR(length=250), autoincrement=False, nullable=False),
    sa.Column('Eye_color', sa.VARCHAR(length=250), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('Id_Personajes', name='people_pkey')
    )
    op.drop_table('personajes')
    # ### end Alembic commands ###
