"""empty message

Revision ID: f3af458c6a2d
Revises: 46a294384f83
Create Date: 2024-10-09 01:31:45.133721

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3af458c6a2d'
down_revision = '46a294384f83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('datos__favoritos',
    sa.Column('id_Favoritos', sa.Integer(), nullable=False),
    sa.Column('user_Id', sa.Integer(), nullable=True),
    sa.Column('Planeta_ID', sa.Integer(), nullable=True),
    sa.Column('Personajes_Id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['Personajes_Id'], ['people.Id_Personajes'], ),
    sa.ForeignKeyConstraint(['Planeta_ID'], ['planetas.ID_Planeta'], ),
    sa.ForeignKeyConstraint(['user_Id'], ['usuario.ID_Usuario'], ),
    sa.PrimaryKeyConstraint('id_Favoritos')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('datos__favoritos')
    # ### end Alembic commands ###
